const types = {
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  SET_ACCESS_TOKEN: "SET_ACCESS_TOKEN",
  REMOVE_ACCESS_TOKEN: "REMOVE_ACCESS_TOKEN",
  TOGGLE_SEARCH: "TOGGLE_SEARCH",

  GET_USER_INFO: "GET_USER_INFO",
  REMOVE_USER_INFO: "REMOVE_USER_INFO",

  INCREASE_COUNT: "INCREASE_COUNT",
  DECREASE_COUNT: "DECREASE_COUNT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT"
};

export default types;
